### PR TITLE
Allow external config file

### PR DESCRIPTION
**Pull request by DarkoKukovec**
Related to #26 

Exposes a `--config` flag for the config.

Scenarios to cover:
* [x] Flag is set, file is valid - load the file
* [x] Flag is set, file is not valid - show an error
* [x] Flag not set - check for the `webpack-canary.conf.js` file in the parent project folder
* [x] Flag not set, default config doesn't exist - show an error

TODO:
* [x] Support `exampleDir` property - #23
* [x] Support `timeout` property
* [x] Update readme
* [x] Test command - #24 
* [x] Figure out why last example is failing (install timeout with npm, weird errors with yarn)

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Wow it looks like we are getting really really close. Is there anything I can do to help? Or any other resources I can throw at ya etc. to help with anything else with this release.

**Comment by DarkoKukovec** [comment]
This feature needs some more polishing (error messages could be better), but I think it's good enough for the first release.
I wanted to also implement #29 and #54, but since they're not essential and with Webpack 4 around the corner, it might be better to put them on hold.

I guess the next steps would be to try this on some loaders/plugins or on webpack itself. We would need a list of dependencies to test this on. I planned to use latest stable versions of webpack-dev-server and extract-text-webpack-plugin, but if there is something that has bigger priority, we can start with it.

**Comment by TheLarkInn** [comment]
Awesome. In fact, I would like this to take its "maiden voyage" for webpack v4 against all the webpack-contrib repos. Let's sync up with @d3viant0ne and the @webpack-contrib/admin-team to see the best way to do this. 

Will be a great first trial run.
@DarkoKukovec will you be willing to create a GitHub issue for better messaging. There are multiple tech writer contribs who specialize in this kind of messaging. I think its a perfect opportunity for them to be more involved post release. 

Otherwise. Let's ship this.

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
This looks great. Incredible work.

**Comment by joshwiens** [comment]
Let's start with etwp as the working test for an eventual update to defaults to update the org.

It's always the problem repo for major Webpack version as well as being one of the most complex test & configuration wise.

**Comment by andreicek** [comment]
@DarkoKukovec already started work on etwp and dev server 😄 Thanks!

**Comment by joshwiens** [comment]
There are a bunch of other Travis changes I was going to roll into adding Canary. If @DarkoKukovec is going to do the initial canary work for etwp, i'll just roll those changes into his PR & then migrate that to defaults.

**Pull request merged**
