### PR TITLE
Support missing readme

### PR DESCRIPTION
**Pull request by DarkoKukovec**
Related to #31

### CODE REVIEW

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
@DarkoKukovec you just need to sign CLI if you haven't already and then you will be good to go.

**Review by andreicek — APPROVED** [review]

**Comment by andreicek** [comment]
I've talked with @DarkoKukovec and he did sign the CLA but the original author didn't. @alistairjcbrown can you please do this?

Thanks!

**Comment by joshwiens** [comment]
As opposed to trying to fight the CLA assistant, it's going to be considerably faster to just create a new branch and commit / PR the change from that.

**Comment by andreicek** [comment]
Agreed, @DarkoKukovec you know what to do 😃

**Comment by alistairjcbrown** [comment]
@andreicek CLA signed

**Comment by andreicek** [comment]
Thanks a bunch!

**Pull request merged**
